# Generated by Django 3.2.9 on 2021-11-20 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='Название товара')),
                ('delivery_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата поступления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('unit_of_measure', models.CharField(max_length=64, verbose_name='Единица измерения')),
                ('producer', models.CharField(max_length=256, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
