# Generated by Django 3.2.9 on 2021-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211125_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ManyToManyField(blank=True, related_name='catalog', to='mainapp.Catalog', verbose_name='Каталог'),
        ),
    ]
