# Generated by Django 3.2.9 on 2021-12-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mainapp', '0005_auto_20211128_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='site',
            field=models.ManyToManyField(to='sites.Site'),
        ),
    ]
