# Generated by Django 3.2.9 on 2021-12-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211202_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images', verbose_name='Изображение товара'),
        ),
    ]
