# Generated by Django 3.2.9 on 2021-12-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mainapp', '0007_auto_20211202_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='site',
        ),
        migrations.AddField(
            model_name='catalog',
            name='site',
            field=models.ManyToManyField(null=True, to='sites.Site'),
        ),
    ]
