# Generated by Django 3.2.9 on 2021-11-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20211125_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catalog',
        ),
        migrations.AddField(
            model_name='product',
            name='catalogs',
            field=models.ManyToManyField(blank=True, related_name='products', to='mainapp.Catalog', verbose_name='Каталог'),
        ),
    ]
